/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated.medications'
import { Route as AuthenticatedMedicationsIndexRouteImport } from './routes/_authenticated.medications.index'
import { Route as AuthenticatedMedicationsIdRouteImport } from './routes/_authenticated.medications.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMedicationsIndexRoute =
  AuthenticatedMedicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedMedicationsIdRoute =
  AuthenticatedMedicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/medications': typeof AuthenticatedMedicationsRouteWithChildren
  '/medications/$id': typeof AuthenticatedMedicationsIdRoute
  '/medications/': typeof AuthenticatedMedicationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/medications/$id': typeof AuthenticatedMedicationsIdRoute
  '/medications': typeof AuthenticatedMedicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/medications': typeof AuthenticatedMedicationsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/medications/$id': typeof AuthenticatedMedicationsIdRoute
  '/_authenticated/medications/': typeof AuthenticatedMedicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/medications'
    | '/medications/$id'
    | '/medications/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/' | '/medications/$id' | '/medications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/medications'
    | '/_authenticated/'
    | '/_authenticated/medications/$id'
    | '/_authenticated/medications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medications/': {
      id: '/_authenticated/medications/'
      path: '/'
      fullPath: '/medications/'
      preLoaderRoute: typeof AuthenticatedMedicationsIndexRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/medications/$id': {
      id: '/_authenticated/medications/$id'
      path: '/$id'
      fullPath: '/medications/$id'
      preLoaderRoute: typeof AuthenticatedMedicationsIdRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
  }
}

interface AuthenticatedMedicationsRouteChildren {
  AuthenticatedMedicationsIdRoute: typeof AuthenticatedMedicationsIdRoute
  AuthenticatedMedicationsIndexRoute: typeof AuthenticatedMedicationsIndexRoute
}

const AuthenticatedMedicationsRouteChildren: AuthenticatedMedicationsRouteChildren =
  {
    AuthenticatedMedicationsIdRoute: AuthenticatedMedicationsIdRoute,
    AuthenticatedMedicationsIndexRoute: AuthenticatedMedicationsIndexRoute,
  }

const AuthenticatedMedicationsRouteWithChildren =
  AuthenticatedMedicationsRoute._addFileChildren(
    AuthenticatedMedicationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
